apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab3
spec:
  tls:
  - hosts:
      - https-example.foo.com
    secretName: lab3-com-tls
  rules:
  - host: lab3.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lab3
            port:
              number: 3000

              
              
